jacob:
# Joint Trajectory ----------------------------------------------------  
  effort_finger_trajectory_controller:
    constraints:
      goal_time: 1.0
      jacob_joint_finger_1:
        goal: 0.02
        trajectory: 0.05
      jacob_joint_finger_2:
        goal: 0.02
        trajectory: 0.05
      jacob_joint_finger_3:
        goal: 0.02
        trajectory: 0.05
      stopped_velocity_tolerance: 0.02
    gains:
      jacob_joint_finger_1:
        d: 0
        i: 0
        i_clamp: 1
        p: 10
      jacob_joint_finger_2:
        d: 0
        i: 0
        i_clamp: 1
        p: 10
      jacob_joint_finger_3:
        d: 0
        i: 0
        i_clamp: 1
        p: 10
    joints:
    - jacob_joint_finger_1
    - jacob_joint_finger_2
    - jacob_joint_finger_3
    type: effort_controllers/JointTrajectoryController
  effort_joint_trajectory_controller:
    constraints:
      goal_time: 1.0
      jacob_joint_1:
        goal: 0.02
        trajectory: 0.05
      jacob_joint_2:
        goal: 0.02
        trajectory: 0.05
      jacob_joint_3:
        goal: 0.02
        trajectory: 0.05
      jacob_joint_4:
        goal: 0.02
        trajectory: 0.05
      jacob_joint_5:
        goal: 0.02
        trajectory: 0.05
      jacob_joint_6:
        goal: 0.02
        trajectory: 0.05
      stopped_velocity_tolerance: 0.02
    gains:
      jacob_joint_1:
        d: 0
        i: 0
        i_clamp: 10
        p: 5000
      jacob_joint_2:
        d: 0
        i: 0
        i_clamp: 10
        p: 5000
      jacob_joint_3:
        d: 0
        i: 0
        i_clamp: 10
        p: 5000
      jacob_joint_4:
        d: 0
        i: 0
        i_clamp: 10
        p: 500
      jacob_joint_5:
        d: 0
        i: 0
        i_clamp: 10
        p: 200
      jacob_joint_6:
        d: 0
        i: 0
        i_clamp: 10
        p: 500
    joints:
    - jacob_joint_1
    - jacob_joint_2
    - jacob_joint_3
    - jacob_joint_4
    - jacob_joint_5
    - jacob_joint_6
    type: effort_controllers/JointTrajectoryController

# Position Controllers ----------------------------------------------------  
  finger_1_position_controller:
    joint: jacob_joint_finger_1
    pid:
      d: 0.3
      i: 0
      p: 0.0
    type: effort_controllers/JointPositionController
  finger_2_position_controller:
    joint: jacob_joint_finger_2
    pid:
      d: 0.3
      i: 0
      p: 2.0
    type: effort_controllers/JointPositionController
  finger_3_position_controller:
    joint: jacob_joint_finger_3
    pid:
      d: 0.3
      i: 0
      p: 5
    type: effort_controllers/JointPositionController

  joint_1_position_controller:
    joint: jacob_joint_1
    pid:
      d: 10
      i: 0
      p: 100
    type: effort_controllers/JointPositionController
  joint_2_position_controller:
    joint: jacob_joint_2
    pid:
      d: 60
      i: 0
      p: 500
    type: effort_controllers/JointPositionController
  joint_3_position_controller:
    joint: jacob_joint_3
    pid:
      d: 20
      i: 0
      p: 35
    type: effort_controllers/JointPositionController
  joint_4_position_controller:
    joint: jacob_joint_4
    pid:
      d: 0.4
      i: 0
      p: 250
    type: effort_controllers/JointPositionController
  joint_5_position_controller:
    joint: jacob_joint_5
    pid:
      d: 0
      i: 200
      p: 250
    type: effort_controllers/JointPositionController
  joint_6_position_controller:
    joint: jacob_joint_6
    pid:
      d: 0.8
      i: 0
      p: 20
    type: effort_controllers/JointPositionController

# Joint State ---------------------------------------------------- 
  joint_state_controller:
    publish_rate: 50
    type: joint_state_controller/JointStateController
